theme = "mellow_trpt"

[editor]
# evil = true
shell = ["/home/apd/.cargo/bin/nu", "-c"]
line-number = "relative"
bufferline = "multiple"
cursorline = true
popup-border = "all"
mouse = false
rulers = [80, 120]

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = false

[keys.normal]
C-o = ":config-open"
C-r = ":config-reload"

C-y = [
  ':sh $env.TEMP_PATH | path join $env.HX_TEMP_FILE | rm -f $in',
  ':insert-output yazi ...%{buffer_name} --chooser-file=%sh{ $env.TEMP_PATH | path join $env.HX_TEMP_FILE }',
  ":open %sh{ $env.TEMP_PATH | path join $env.HX_TEMP_FILE | cat $in }",
  ':redraw'
]

# Some nice Helix stuff
C-h = "select_prev_sibling"
C-j = "shrink_selection"
C-k = "expand_selection"
C-l = "select_next_sibling"

# lazygit
C-s = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw", ":reload-all"]

[keys.insert.k]
j = "normal_mode"

[keys.insert]
# escape the madness! no more fighting with the cursor! or with multiple cursors!
esc = ["collapse_selection", "normal_mode"]
"C-["= ["collapse_selection", "normal_mode"]
