[[language]]
name = "go"
auto-format = true
language-servers = [ "gopls", "golangci-lint-lsp" ]
[language-server.golangci-lint-lsp]
command = "golangci-lint-langserver"
[language-server.golangci-lint-lsp.config]
command = ["golangci-lint", "run", "--out-format", "json", "--issues-exit-code=1"]


[[language]]
name = "nim"
formatter = { command = "nimpretty" }
auto-format = true

[[language]]
name = "c"
formatter = { command = "clang-format" }
auto-format = true

[[language]]
name = "python"
formatter = { command = "black" }
auto-format = true

[language.debugger]
name = "debugpy"
transport = "stdio"
command = "python3"
args = ["-m",  "debugpy.adapter"]

[language-server.pylsp.config.pylsp.plugins]
black.enabled = true

[[language.debugger.templates]]
name = "source"
request = "launch"
completion = [ { name = "entrypoint", completion = "filename", default = "." } ]
args = { mode = "debug", program = "{0}" }

[[language]]
name = "json"
auto-format = true
