#!/usr/bin/env bash
if [ -f ~/.profile ]; then
	. ~/.profile
fi

# If not running interactively, we're done

case $- in
  *i*) ;;
    *) return;;
esac

if [ -f ~/.bashrc ]; then
  . ~/.bashrc
fi

. "$HOME/.local/bin/env"

# KDB-X Installation Configuration - Wed Dec 24 04:19:59 AM EST 2025
export PATH="/home/apd/.kx/bin:$PATH"
# End KDB-X Installation Configuration
