#!/usr/bin/env bash
export XDG_CONFIG_HOME="$HOME/.config"
export BASH_IT="$HOME/.bash_it"
export BASH_IT_THEME='bobby'
# export BASH_IT_THEME='powerline-multiline'
export THEME_CHECK_SUDO='true'
unset MAILCHECK
export SCM_CHECK=true
export BASH_IT_AUTOMATIC_RELOAD_AFTER_CONFIG_CHANGE=1
# export GIT_HOSTING='git@git.domain.com'
# export IRC_CLIENT='irssi'
# Set this to the location of your work or project folders
# BASH_IT_PROJECT_PATHS="${HOME}/Projects:/Volumes/work/src"

HX=/home/apd/local/bin/hx

alias em="$HOME/local/bin/emacs-nw"
alias vimrc="$HX $HOME/.config/nvim/init.vim"
alias brc="$HX $HOME/.bashrc"
alias brofile="$HX $HOME/.bash_profile"
alias profile="$HX $HOME/.profile"
alias rebash=". $HOME/.bash_profile"
alias barebash="bash --norc"
alias zconf="$HX $HOME/.config/zellij/config.kdl"
alias zlay="$HX $HOME/.config/zellij/layouts/default.kdl"
alias wconf="$HX $HOME/.config/wezterm/wezterm.lua"
alias econf="$HX $HOME/.config/emacs/init.el"
alias nuconf="$HX $HOME/.config/nushell/config.nu"
alias nuenv="$HX $HOME/.config/nushell/env.nu"
alias kconf="$HX $HOME/.config/kitty/kitty.conf"
alias sconf="$HX $HOME/.config/sway/config"
alias barconf="$HX $HOME/.config/waybar/config.jsonc"

alias gs="git status"
alias gco="git checkout"
alias gsw="git switch"

# bash specific
test -r "$HOME/.fzf.bash" && . "$HOME/.fzf.bash"
test -r "$BASH_IT/bash_it.sh" && . "$BASH_IT/bash_it.sh"
test -r "$HOME/.local/bin/mise" && eval "$($HOME/.local/bin/mise activate bash)"


function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		builtin cd -- "$cwd"
	fi
	rm -f -- "$tmp"
}
